[supervisord]
nodaemon=true

[program:laravel-web]
command=php artisan serve --host=0.0.0.0 --port=8000
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/log/web.log
stderr_logfile=/var/log/web.err.log
user=www-data

[program:laravel-queue]
command=php artisan queue:work database --sleep=3 --tries=3
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/log/queue.log
stderr_logfile=/var/log/queue.err.log
user=www-data
