[supervisord]
nodaemon=true

[program:laravel-web]
command=php artisan serve --host=0.0.0.0 --port=8000
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/log/web.log
stderr_logfile=/var/log/web.err.log
user=www-data

[program:laravel-queue-database]
command=php artisan queue:work database --sleep=3 --tries=3
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/var/log/queue-database.log
stderr_logfile=/var/log/queue-database.err.log
user=www-data

[program:laravel-queue-redis]
command=php artisan queue:work redis --queue=redis-queue --sleep=1 --tries=5 --timeout=90
directory=/var/www
autostart=true
autorestart=true
numprocs=2
process_name=%(program_name)s_%(process_num)s
stdout_logfile=/var/log/queue-redis_%(process_num)s.log
stderr_logfile=/var/log/queue-redis_%(process_num)s.err.log
user=www-data
